// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Supavolt.Api.Infrastructure;

#nullable disable

namespace Supavolt.Api.Migrations
{
    [DbContext(typeof(SupavoltDbContext))]
    partial class SupavoltDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Supavolt.Api.Infrastructure.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_invites");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_invites_token_hash");

                    b.HasIndex("OrgId", "Email")
                        .HasDatabaseName("ix_invites_org_id_email");

                    b.ToTable("invites", (string)null);
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.OrgMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_org_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_org_members_user_id");

                    b.HasIndex("OrgId", "UserId")
                        .HasDatabaseName("ix_org_members_org_id_user_id");

                    b.ToTable("org_members", (string)null);
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AnonKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("anon_key");

                    b.Property<string>("AuthJwtSecret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_jwt_secret");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DbRolePassword")
                        .HasColumnType("text")
                        .HasColumnName("db_role_password");

                    b.Property<string>("DbSchema")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("db_schema");

                    b.Property<string>("GithubClientId")
                        .HasColumnType("text")
                        .HasColumnName("github_client_id");

                    b.Property<string>("GithubClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("github_client_secret");

                    b.Property<string>("GoogleClientId")
                        .HasColumnType("text")
                        .HasColumnName("google_client_id");

                    b.Property<string>("GoogleClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("google_client_secret");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("key_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_url");

                    b.Property<string>("RedirectUrls")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("redirect_urls");

                    b.Property<string>("ServiceRoleKeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_role_key_hash");

                    b.Property<string>("SiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("site_url");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("DbSchema")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_db_schema");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_projects_org_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_slug");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.ProjectAuthToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_project_auth_tokens");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_auth_tokens_project_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_project_auth_tokens_token_hash");

                    b.ToTable("project_auth_tokens", (string)null);
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.QueryHistoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ExecutionTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("execution_time_ms");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<long>("RowCount")
                        .HasColumnType("bigint")
                        .HasColumnName("row_count");

                    b.Property<string>("Sql")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sql");

                    b.HasKey("Id")
                        .HasName("pk_query_history");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .HasDatabaseName("ix_query_history_project_id_created_at");

                    b.ToTable("query_history", (string)null);
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.StorageBucket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_storage_buckets");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_storage_buckets_project_id_name");

                    b.ToTable("storage_buckets", (string)null);
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.StorageObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BucketId")
                        .HasColumnType("uuid")
                        .HasColumnName("bucket_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_storage_objects");

                    b.HasIndex("BucketId")
                        .HasDatabaseName("ix_storage_objects_bucket_id");

                    b.ToTable("storage_objects", (string)null);
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.Invite", b =>
                {
                    b.HasOne("Supavolt.Api.Infrastructure.Organization", "Org")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invites_organizations_org_id");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.OrgMember", b =>
                {
                    b.HasOne("Supavolt.Api.Infrastructure.Organization", "Org")
                        .WithMany("Members")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_members_organizations_org_id");

                    b.HasOne("Supavolt.Api.Infrastructure.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_members_users_user_id");

                    b.Navigation("Org");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.Project", b =>
                {
                    b.HasOne("Supavolt.Api.Infrastructure.Organization", "Org")
                        .WithMany("Projects")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_organizations_org_id");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.ProjectAuthToken", b =>
                {
                    b.HasOne("Supavolt.Api.Infrastructure.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_auth_tokens_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.QueryHistoryItem", b =>
                {
                    b.HasOne("Supavolt.Api.Infrastructure.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_query_history_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.RefreshToken", b =>
                {
                    b.HasOne("Supavolt.Api.Infrastructure.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.StorageBucket", b =>
                {
                    b.HasOne("Supavolt.Api.Infrastructure.Project", "Project")
                        .WithMany("Buckets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_storage_buckets_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.StorageObject", b =>
                {
                    b.HasOne("Supavolt.Api.Infrastructure.StorageBucket", "Bucket")
                        .WithMany("Objects")
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_storage_objects_storage_buckets_bucket_id");

                    b.Navigation("Bucket");
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.Organization", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.Project", b =>
                {
                    b.Navigation("Buckets");
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.StorageBucket", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("Supavolt.Api.Infrastructure.User", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
