using System.Security.Cryptography;
using Microsoft.Extensions.Options;
using Npgsql;
using Supavolt.Api.Infrastructure.Configuration;
using Supavolt.Contracts;

namespace Supavolt.Api.Infrastructure.Tenancy;

public interface ITenantConnectionFactory
{
    /// <summary>Pooled control-plane connection: migrations, DDL, introspection.</summary>
    Task<NpgsqlConnection> OpenAdminAsync(CancellationToken ct = default);

    /// <summary>Least-privilege connection for user-authored SQL and the generated data API.</summary>
    Task<NpgsqlConnection> OpenTenantAsync(CancellationToken ct = default);

    /// <summary>
    /// A project's own login role: the only connection user-authored SQL runs on. Unlike the
    /// shared tenant role it has no grant on any other project's schema.
    /// </summary>
    Task<NpgsqlConnection> OpenProjectAsync(string role, string password, CancellationToken ct = default);

    /// <summary>Direct, non-pooled connection for LISTEN. Never returned to a shared pool.</summary>
    NpgsqlConnection CreateListenConnection();
}

public sealed class TenantConnectionFactory(IOptions<DatabaseOptions> options) : ITenantConnectionFactory
{
    private readonly DatabaseOptions _o = options.Value;

    public async Task<NpgsqlConnection> OpenAdminAsync(CancellationToken ct = default)
    {
        var conn = new NpgsqlConnection(_o.ConnectionString);
        await conn.OpenAsync(ct);
        return conn;
    }

    public async Task<NpgsqlConnection> OpenTenantAsync(CancellationToken ct = default)
    {
        var conn = new NpgsqlConnection(_o.TenantConnectionString);
        await conn.OpenAsync(ct);
        return conn;
    }

    public async Task<NpgsqlConnection> OpenProjectAsync(string role, string password, CancellationToken ct = default)
    {
        // Same host and database as the tenant connection, different credentials. Npgsql pools per
        // connection string, so keep each project's pool small.
        var builder = new NpgsqlConnectionStringBuilder(_o.TenantConnectionString)
        {
            Username = role,
            Password = password,
            MaxPoolSize = 5,
            ConnectionIdleLifetime = 60
        };

        var conn = new NpgsqlConnection(builder.ConnectionString);
        await conn.OpenAsync(ct);
        return conn;
    }

    public NpgsqlConnection CreateListenConnection() => new(_o.DirectConnectionString);
}

public static class SchemaNames
{
    /// <summary>Where the shared realtime trigger function lives.</summary>
    public const string Internal = "supavolt_internal";

    public const string RealtimeChannel = "supavolt_events";

    public static string NewProjectSchema() => $"proj_{RandomNumberGenerator.GetHexString(8, lowercase: true)}";

    /// <summary>
    /// Project schemas are generated by us, so the shape is known exactly. Validating against the
    /// narrow pattern rather than a general identifier regex means a corrupted row cannot become DDL.
    /// </summary>
    public static SqlIdentifier ValidateProjectSchema(string schema)
    {
        if (schema.Length != 13 || !schema.StartsWith("proj_", StringComparison.Ordinal)
            || !schema.AsSpan(5).ContainsOnlyLowerHex())
            throw new InvalidIdentifierException(schema, "project schema");

        return new SqlIdentifier(schema, "project schema");
    }

    private static bool ContainsOnlyLowerHex(this ReadOnlySpan<char> span)
    {
        foreach (var c in span)
            if (!(c is >= '0' and <= '9' or >= 'a' and <= 'f'))
                return false;

        return span.Length > 0;
    }
}

public static class ColumnTypes
{
    /// <summary>
    /// The caller sends a ColumnType enum, so an unknown type fails model binding with a 400
    /// instead of reaching SQL. The original accepted a string and fell back to TEXT.
    /// </summary>
    public static string ToSql(this ColumnType type) => type switch
    {
        ColumnType.Text => "TEXT",
        ColumnType.Integer => "INTEGER",
        ColumnType.Bigint => "BIGINT",
        ColumnType.Boolean => "BOOLEAN",
        ColumnType.Timestamp => "TIMESTAMPTZ",
        ColumnType.Uuid => "UUID",
        ColumnType.Jsonb => "JSONB",
        ColumnType.Numeric => "NUMERIC",
        _ => throw new ArgumentOutOfRangeException(nameof(type), type, "Unsupported column type")
    };

    public static ColumnType FromPg(string pgType) => pgType switch
    {
        "text" or "character varying" or "char" or "character" => ColumnType.Text,
        "integer" or "smallint" => ColumnType.Integer,
        "bigint" => ColumnType.Bigint,
        "boolean" => ColumnType.Boolean,
        "timestamp with time zone" or "timestamp without time zone" => ColumnType.Timestamp,
        "uuid" => ColumnType.Uuid,
        "jsonb" or "json" => ColumnType.Jsonb,
        "numeric" or "double precision" or "real" => ColumnType.Numeric,
        _ => ColumnType.Text
    };

    /// <summary>
    /// Allow-listed function defaults. Anything else becomes a quoted literal, and a literal
    /// containing a parenthesis is rejected rather than guessed at.
    /// </summary>
    private static readonly string[] AllowedFunctions = ["now()", "gen_random_uuid()", "current_timestamp"];

    public static string FormatDefault(string raw, ColumnType type)
    {
        var trimmed = raw.Trim();

        foreach (var fn in AllowedFunctions)
            if (string.Equals(trimmed, fn, StringComparison.OrdinalIgnoreCase))
                return fn;

        if (trimmed.Contains('(') || trimmed.Contains(')'))
            throw new InvalidIdentifierException(trimmed, "column default");

        return type switch
        {
            ColumnType.Boolean when bool.TryParse(trimmed, out var b) => b ? "TRUE" : "FALSE",
            ColumnType.Integer or ColumnType.Bigint when long.TryParse(trimmed, out var l) => l.ToString(),
            ColumnType.Numeric when decimal.TryParse(trimmed, out var d) => d.ToString(),
            ColumnType.Jsonb => $"'{trimmed.Replace("'", "''")}'::jsonb",
            _ => $"'{trimmed.Replace("'", "''")}'"
        };
    }
}
