package dev.supavolt.api.infrastructure.tenancy;

import dev.supavolt.api.common.Tokens;

public final class SchemaNames {

    /** Where the shared realtime trigger function lives. */
    public static final String INTERNAL = "supavolt_internal";

    public static final String REALTIME_CHANNEL = "supavolt_events";

    private SchemaNames() {
    }

    public static String newProjectSchema() {
        return "proj_" + Tokens.randomHex(8);
    }

    /**
     * Project schemas are generated by us, so the shape is known exactly. Validating against the
     * narrow pattern rather than a general identifier pattern means a corrupted row cannot become DDL.
     */
    public static SqlIdentifier validateProjectSchema(String schema) {
        if (schema == null || !schema.matches("proj_[0-9a-f]{8}"))
            throw new InvalidIdentifierException(schema == null ? "" : schema, "project schema");

        return new SqlIdentifier(schema, "project schema");
    }
}
